### ISSUE TITLE
pure as3 version of wck

### ISSUE THREAD

**Issue by HiWill** [jesses/wck#12]
if there pure as3 version of wck ?

**Comment by jesses** [comment]
You mean without alchemy? Nope.

**Comment by HiWill** [comment]
Yes , 
one reason is pure as3 get better performance in mobile (ios and android)
another ,  use alchemy with stage3d is not free;

**Comment by HiWill** [comment]
By the way, wck is best flash physic engine I have found, Thank you for your great contribution!

**Comment by jesses** [comment]
No problem, hope you make something cool with it.

I'm hoping the new Alchemy that Adobe is cooking up will be more mobile friendly. Unfortunately stage3D graphics are separate from the traditional Flash display hierarchy, so the drag-and-drop nature of WCK can't really be used with it.
