### ISSUE TITLE
Null Reference in drag handler

### ISSUE THREAD

**Issue by Echooff3** [jesses/wck#2]
I attempted to go through the steps in the wiki and I get the following error when trying to drag "myRect"

TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at wck::BodyShape/handleDragStart()

b2body is null in wck::BodyShape as well as a few other properties named "body"

Flash CS4 / Mac OSX 10.5.8

**Comment by jesses** [comment]
Is your bodyshape inside a wck.World object?

**Comment by Echooff3** [comment]
It's on the stage inside the overlapping walls.

**Comment by jesses** [comment]
Your scene should be setup like this:

On the stage: A symbol that extends wck.World

In the wck.World symbol: Your Boxes, BodyShapes, etc.

So your walls / boxes etc. shouldn't be directly on the stage. They need to be in a World.

**Comment by Echooff3** [comment]
That was it! Nicely Done!!!

**Comment by jesses** [comment]
...and closed :)
