### ISSUE TITLE
wrong url at homepage

### ISSUE THREAD

**Issue by birbilis** [jesses/wck#21]
at github repo homepage, it has link for Box2D manual
http://http//www.box2d.org/manual.html
which is obviously wrong (remove the http// after http://)

**Comment by jesses** [comment]
What page? Everything looks fine from here.

**Comment by birbilis** [comment]
sorry, that is the page with the issue: https://github.com/jesses/wck/wiki/box2d-flash-alchemy-port

**Comment by jesses** [comment]
Thanks, URL fixed.
