### ISSUE TITLE
Memory leaks on the AS3 side of WCK

### ISSUE THREAD

**Issue by tynril** [jesses/wck#7]
It seems to be strong managed memory leaks on the AS3 wrapper. Simply creating a world, populating it with a few bodies and calling `destroy()` on it let the managed memory with many circular references. Those objects cannot be used anymore, but will remain in memory (well, partially due to the poor AVM+ garbage collector).

That should be fixed by destroying references on various `destroy()` methods.

**Comment by jesses** [comment]
Are you sure this is not just the overhead of loading the Alchemy resources? Once b2Base.initialize() is called there's going to be a bunch of Alchemy related objects in Memory for good. On the forum we've been discussing strategies for releasing these, but that's only beneficial if for some reason your SWF wants to dump Box2D completely and for good.

**Comment by tynril** [comment]
After further investigation, it seems that all objects are created from within Alchemy (some V2 instances), and also, I forgot to call b2Def.destroy(). Sorry!
