### ISSUE TITLE
Getting AlchemyExit Errors

### ISSUE THREAD

**Issue by quinnhoener** [jesses/wck#9]
I'm having an issue with WCK where I get these set of errors:

Assertion failed: (typeA == b2_dynamicBody || typeB == b2_dynamicBody), function SolveTOI, file ../Box2D/Dynamics/b2World.cpp, line 607.

[object AlchemyExit]
    at Function/<anonymous>()
    at Function/<anonymous>()
    at Box2DAS.Dynamics::b2World/HandleStep()
    at flash.events::EventDispatcher/dispatchEventFunction()
    at flash.events::EventDispatcher/dispatchEvent()
    at Box2DAS.Common::b2EventDispatcher/dispatchEvent()
    at Box2DAS.Dynamics::b2World/Step()
    at wck::World/step()
Assertion failed: (IsLocked() == false), function DestroyBody, file ../Box2D/Dynamics/b2World.cpp, line 130.

[object AlchemyExit]
    at Function/<anonymous>()
    at Function/<anonymous>()
    at Box2DAS.Dynamics::b2Body/destroy()
    at Function/<anonymous>()
    at Function/http://adobe.com/AS3/2006/builtin::apply()
    at wck::World/step()

Here's a description of how I'm using WCK. 
I have 2 instances of the world to catch 2 different sets of physics that I don't want to collide with each other. I'm never destroying the world ( i have a trace in World::destroy() ), but saving a reference to it and only calling parent.visible = false to not show it so that I can avoid WCK automatically destroying the physics world when removing from the display list. I'm using an Object pool for the physics objects that need to keep re-spawning (in this case they are basketballs). So the basketballs are being added and removed from the stage, but this seems to work fine during gameplay. These errors aren't thrown every time that the level ends and moves to the next level, in which everything is reset to their initial positions, but happens seemingly randomly. It's never the same amount of levels into the game when the error occurs. 

My thoughts, something is getting cleaned up on the C++ side of things, but the as3 object still has a pointer, which is now null. I'm fairly new to Box2D and WCK so that's just a guess. 

Any help on this would be greatly appreciated. 

Thank you.

**Comment by jesses** [comment]
Looks like you're trying to do something while the time step is running that Box2D doesn't like. For example, there are certain things you cannot do in a contact callback function - you have to wait until the time step is done. You can call doOutsideTimeStep and pass it a function if you want to solve this the quick and easy way. 2nd one looks like you're destroying a body, for example.

**Comment by quinnhoener** [comment]
Thank you, that seemed to have solved my problem. I had a contact listener for when the basketball made it through the hoop. I was setting the world to pause between level ending and level starting. I'm guessing that if you made the last basket that pushed to the next level, if the basketball was still on the sensor when it called pause then it would throw this error. I'm now removing the event listener right before setting the world to paused and that seems to be working wonderfully! I had originally kept the listener because I wasn't ever destroying the world so I thought it wouldn't matter if I kept adding and removing the listener for it. 

Thank you for your quick reply as well.

**Comment by quinnhoener** [comment]
I lied... Still getting this one error:

Assertion failed: (typeA == b2_dynamicBody || typeB == b2_dynamicBody), function SolveTOI, file ../Box2D/Dynamics/b2World.cpp, line 607.
[object AlchemyExit]
    at Function/<anonymous>()
    at Function/<anonymous>()
    at Box2DAS.Dynamics::b2World/HandleStep()
    at flash.events::EventDispatcher/dispatchEventFunction()
    at flash.events::EventDispatcher/dispatchEvent()
    at Box2DAS.Common::b2EventDispatcher/dispatchEvent()
    at Box2DAS.Dynamics::b2World/Step()
    at wck::World/step()

**Comment by jesses** [comment]
Are you changing any bodies mid-timestep from dynamic to static / kinematic? It's throwing that error because it's trying to process contacts and finds one between 2 static bodies.

**Comment by quinnhoener** [comment]
What you said flipped the understanding switch in my brain. I greatly appreciate your help with all this. I'm fairly certain that my problem is fixed now. 

WCK rule #28: Don't mess with physics when the World is paused.

Thanks again!
